swiftmailer:
    transport: smtp
    username: 2e7cd8ccecd400ca389bf3845d23eb27
    password: b029a74482acc1b5eec682a289ccb240
    host: in-v3.mailjet.com
    port: '587'
    encryption: tls
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
