swiftmailer:
    transport: smtp
    username: 42271d6fe5e32f29719e16b3f3ea980d
    password: bcd8b6ac14d28e77e0bef36107acf8b5
    host: in-v3.mailjet.com
    port: '587'
    encryption: tls
    auth-mode: login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
